### ISSUE TITLE
JSONDecodeError on launch

### ISSUE THREAD

**Issue by Verkhovskyi** [oskvr37/tiddl#45]
After installation trying to use `tiddl` to set up auth token, but instead getting the same errors on Windows and Ubuntu:

<img width="1353" alt="Screenshot 2024-11-09 at 2 10 09 PM" src="https://github.com/user-attachments/assets/83e7d2da-b4c8-4fcd-9583-5ce3b8e83e2e">
<img width="721" alt="Screenshot 2024-11-09 at 2 27 44 PM" src="https://github.com/user-attachments/assets/ee40ac1a-1066-4da7-ac35-3235b69d19ce">

I can use `tiddl -h` and it shows help message without errors, but any other actions leads to mentioned error.

**Comment by oskvr37** [comment]
It seems to be a problem with getDeviceAuth function, probably there is an error on request to Tidal api.
Do you use proxy or is Tidal banned on your network?
 
Please edit [this function](https://github.com/oskvr37/tiddl/blob/e28305fe620de5c635e8f5534c38faaba947e547/tiddl/auth.py#L9) in your local code to the code below, run `tiddl --verbose` and show me results

```py
def getDeviceAuth() -> AuthDeviceResponse:
    req = request(
        "POST",
        f"{AUTH_URL}/device_authorization",
        data={"client_id": CLIENT_ID, "scope": "r_usr+w_usr+w_sub"},
    )

    print(req.status_code, req.text)

    return req.json()
 ```

**Comment by Darkloke** [comment]
I have the same problem and i suppose this is because Tidal blocked in my country. I was able to launch Tiddl through Proxifier by adding rule for python.exe to be run via proxy.

Here is --verbose results:

`C:\Users\Darkloke>tiddl --verbose
←[0;34m[ TIDDL ] ←[0;36mmain ←[0mNamespace(input=[], file_template=None, download_path=None, file_extension=None, quality=None, include_singles=False, save_options=False, input_file='', no_skip=False, silent=False, verbose=True, no_color=False)←[0m
←[0;34m[ Config ] ←[0;36m__init__ ←[0mloaded {'download_path': 'C:\\Users\\Darkloke/tidal_download', 'track_quality': 'HIGH', 'track_template': '{artist}/{title}', 'album_template': '{artist}/{album}/{title}', 'playlist_template': '{playlist}/{title}', 'file_extension': ''}←[0m
←[0;34m[ Config ] ←[0;36mupdate ←[0mupdating←[0m
←[0;34m[ Config ] ←[0;36m_save ←[0m{'download_path': 'C:\\Users\\Darkloke/tidal_download', 'track_quality': 'HIGH', 'track_template': '{artist}/{title}', 'album_template': '{artist}/{album}/{title}', 'playlist_template': '{playlist}/{title}', 'file_extension': ''}←[0m
←[0;34m[ Config ] ←[0;36mupdate ←[0mupdated←[0m
403 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: Vbm4xn2zMHHNF8bi44K5nVUvNn31BvTGrFTektUE4EV6kMmz7t1yBA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
Traceback (most recent call last):
  File "C:\Users\Darkloke\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Darkloke\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Darkloke\AppData\Local\Programs\Python\Python313\Lib\json\decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Darkloke\AppData\Local\Programs\Python\Python313\Lib\json\decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Darkloke\AppData\Local\Programs\Python\Python313\Scripts\tiddl.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\Darkloke\AppData\Local\Programs\Python\Python313\Lib\site-packages\tiddl\__init__.py", line 68, in main
    auth = getDeviceAuth()
  File "C:\Users\Darkloke\AppData\Local\Programs\Python\Python313\Lib\site-packages\tiddl\auth.py", line 18, in getDeviceAuth
    return req.json()
           ~~~~~~~~^^
  File "C:\Users\Darkloke\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by oskvr37** [comment]
I can not help you guys as long as Tidal is not working in your country.
The only thing I can do is to add proxy support

**Comment by Darkloke** [comment]
> I can not help you guys as long as Tidal is not working in your country. The only thing I can do is to add proxy support

Ofc. I am only talking here about handling this exception, so a user could see a warning and not just an error text. :)

**Comment by Verkhovskyi** [comment]
Thank you for your replies, I didn't know Tidal is blocking access from countries they are not officially working in
